### ISSUE TITLE
tabBarItem.redDotBoderColor，崩溃现象；

### ISSUE THREAD

**Issue by nice2m** [Mr-yuwei/Yeebadge#3]
现已修复

https://github.com/nice2m/Yeebadge

enjoy ~ 🎉🙏

**Comment by Mr-yuwei** [comment]
thanks

**Comment by nice2m** [comment]
您看一下这个Pull Rrequest，是否符合最初设计，如果没有问题，建议合并

**Comment by Mr-yuwei** [comment]
好的，非常感谢。<br>
tabBarItem闪退的工程或者堆栈有吗，我想验证一下这个问题。<br>
我测试的时候没有发现这个问题 :flushed:

**Comment by Mr-yuwei** [comment]
> 好的，非常感谢。
> 
> tabBarItem闪退的工程或者堆栈有吗，我想验证一下这个问题。
> 
> 我测试的时候没有发现这个问题 😳
